services:
  # TODO npm install step with deps
  web_dev:
    image: node:24-alpine
    working_dir: /app
    ports:
      - "3000:5173"
    volumes:
      - ./web/:/app/web
      - ./node_modules/:/app/node_modules
      - ./package.json/:/app/package.json
      - ./package-lock.json/:/app/package-lock.json
    command: npm run web:dev
